### ISSUE TITLE
Some CSVs dumped by xEdit are not readable by Modsvaskr

### ISSUE THREAD

**Issue by Muriel-Salvan** [Muriel-Salvan/modsvaskr#59]
When reading the CSV, Modsvaskr crashes with this exception (user report):

[ 2021-02-01 21:21:46 ] - [ Ui ] - Unhandled exception: Illegal quoting in line 145600.
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:879:in `parse_quotable_robust'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:818:in `block in parse_quotable_loose'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:94:in `block in each_line'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:70:in `each_line'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:70:in `each_line'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:779:in `parse_quotable_loose'
C:/Ruby26-x64/lib/ruby/2.6.0/csv/parser.rb:303:in `parse'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:1236:in `each'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:1236:in `each'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:1245:in `to_a'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:1245:in `read'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:714:in `block in read'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:657:in `open'
C:/Ruby26-x64/lib/ruby/2.6.0/csv.rb:714:in `read'
D:/Games/SkyrimSE Utilities/Modsvaskr/vendor/bundle/ruby/2.6.0/gems/modsvaskr-0.1.7/lib/modsvaskr/tests_suites/exterior_cell.rb:17:in `discover_tests'

Need to get an example of such CSV to better understand the underlying issue.

**Comment by Tako-kun01** [comment]
[Modsvaskr_ExportedDumpInfo.zip](https://github.com/Muriel-Salvan/modsvaskr/files/5917045/Modsvaskr_ExportedDumpInfo.zip)

**Comment by primem0ver** [comment]
[Modsvaskr_ExportedDumpInfo.csv](https://github.com/Muriel-Salvan/modsvaskr/files/9079924/Modsvaskr_ExportedDumpInfo.csv)
[Modsvaskr.log](https://github.com/Muriel-Salvan/modsvaskr/files/9079925/Modsvaskr.log)

Getting the same error.  I posted an "issue" but then found this.
